// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3z5UtkIIK_Tlt-jSm6pjP3pRIwa6TIEY',
    appId: '1:1042892656235:web:87b94d925fd3ff0625ab2e',
    messagingSenderId: '1042892656235',
    projectId: 'to-do-app-b8da7',
    authDomain: 'to-do-app-b8da7.firebaseapp.com',
    storageBucket: 'to-do-app-b8da7.firebasestorage.app',
    measurementId: 'G-C8Q81XD95F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGaoVvJ0-5eaZmaI4jEkPSbNmcga_h5Z0',
    appId: '1:1042892656235:android:06eefd1637fb9d5425ab2e',
    messagingSenderId: '1042892656235',
    projectId: 'to-do-app-b8da7',
    storageBucket: 'to-do-app-b8da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDScNvSmUvm3-_v12f-s14bfPj9xRqvs',
    appId: '1:1042892656235:ios:0a8dc39c1a50098d25ab2e',
    messagingSenderId: '1042892656235',
    projectId: 'to-do-app-b8da7',
    storageBucket: 'to-do-app-b8da7.firebasestorage.app',
    iosBundleId: 'com.example.todaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDScNvSmUvm3-_v12f-s14bfPj9xRqvs',
    appId: '1:1042892656235:ios:0a8dc39c1a50098d25ab2e',
    messagingSenderId: '1042892656235',
    projectId: 'to-do-app-b8da7',
    storageBucket: 'to-do-app-b8da7.firebasestorage.app',
    iosBundleId: 'com.example.todaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3z5UtkIIK_Tlt-jSm6pjP3pRIwa6TIEY',
    appId: '1:1042892656235:web:3b01b628f9aa563325ab2e',
    messagingSenderId: '1042892656235',
    projectId: 'to-do-app-b8da7',
    authDomain: 'to-do-app-b8da7.firebaseapp.com',
    storageBucket: 'to-do-app-b8da7.firebasestorage.app',
    measurementId: 'G-SVBT4BZB12',
  );
}
